apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot2-may1-4
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/chatbot2-may1-4:ddeab8879e7cf78392adbc05607eb51e9892c81b@sha256:83e04b0df0cf2f6d76d9b42adc200cd5efc32c62176d449b6dc6188890b90d69 # use pre-built to bootstrap
          name: app-inference
